// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG84WVSyTiT05V0XVcz5V0JrPGmQnCPw4',
    appId: '1:198908255277:web:2fb8e42f9de5eb44ccaca4',
    messagingSenderId: '198908255277',
    projectId: 'snap-shot-ecommerce',
    authDomain: 'snap-shot-ecommerce.firebaseapp.com',
    storageBucket: 'snap-shot-ecommerce.firebasestorage.app',
    measurementId: 'G-NRZYYP7KQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQhvlL0mJXzmtQwCQwiKgT5_v5knH4gNU',
    appId: '1:198908255277:android:28d7056a0b913bc4ccaca4',
    messagingSenderId: '198908255277',
    projectId: 'snap-shot-ecommerce',
    storageBucket: 'snap-shot-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwnVFB8aBOAyC8_4H_UjeU8MU7Z9HNBbg',
    appId: '1:198908255277:ios:f6a303f79cf6ada0ccaca4',
    messagingSenderId: '198908255277',
    projectId: 'snap-shot-ecommerce',
    storageBucket: 'snap-shot-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.snapShot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwnVFB8aBOAyC8_4H_UjeU8MU7Z9HNBbg',
    appId: '1:198908255277:ios:f6a303f79cf6ada0ccaca4',
    messagingSenderId: '198908255277',
    projectId: 'snap-shot-ecommerce',
    storageBucket: 'snap-shot-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.snapShot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG84WVSyTiT05V0XVcz5V0JrPGmQnCPw4',
    appId: '1:198908255277:web:376a98e8f4c0215eccaca4',
    messagingSenderId: '198908255277',
    projectId: 'snap-shot-ecommerce',
    authDomain: 'snap-shot-ecommerce.firebaseapp.com',
    storageBucket: 'snap-shot-ecommerce.firebasestorage.app',
    measurementId: 'G-JKKCX4CYE1',
  );
}
